project:
  type: website

website:
  title: "Torodd F. Ottestad"
  site-url: https://lektorodd.github.io
  description: "Blogg om digitale tips og triks i skulen"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lektorodd/lektorodd.github.io
      - icon: mastodon
        href: https://snabelen.no/@torodd
      - icon: twitter
        href: https://twitter.com/lektorodd
      - icon: linkedin
        href: https://linkedin.com/in/torodd-ottestad-b2583a59
      - icon: rss-fill
        href: index.xml
format:
  html:
    theme: 
    - journal
    - custom.scss


execute:
  freeze: auto  
comments:
  giscus:
    repo: lektorodd/lektorodd.github.io



