project:
  type: website

website:
  title: "Torodd F. Ottestad"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lektorodd
      - icon: twitter
        href: https://twitter.com/lektorodd
      - icon: linkedin
        href: https://linkedin.com/in/torodd-ottestad-b2583a59
format:
  html:
    theme: cosmo
    css: styles.css



