project:
  type: website

website:
  title: "Torodd F. Ottestad"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lektorodd/lektorodd.github.io
      - icon: mastodon
        href: https://snabelen.no/@torodd
      - icon: twitter
        href: https://twitter.com/lektorodd
      - icon: linkedin
        href: https://linkedin.com/in/torodd-ottestad-b2583a59
format:
  html:
    theme: journal
    css: styles.css

comments:
  giscus:
    repo: lektorodd/lektorodd.github.io



