project:
  type: website

website:
  title: "Torodd F. Ottestad"
  site-url: https://lektorodd.github.io
  description: "Lagring for tankar, utprøvingar og løysingsforslag. Det meste er pythonrelatert i større eller mindre grad."
  navbar:
    left:
      - text: "Blogg"
        href: blogg.qmd
        icon: lightbulb
      - text: "Løysingsforslag"
        href: lf.qmd
        icon: calculator
      - text: "Mattebok"
        href: https://lektorodd.github.io/mattebok
        icon: book
      - text: "Om meg"
        href: about.qmd
        icon: person
    right:
   
      - icon: github
        href: https://github.com/lektorodd/lektorodd.github.io
      - icon: clouds-fill
        href: https://bsky.app/profile/torodd.bsky.social
      - icon: youtube
        href: https://www.youtube.com/channel/UCWfDrIj3Mq3Niz77HJ6cTNg
      - icon: linkedin
        href: https://linkedin.com/in/torodd-ottestad-b2583a59
      - icon: rss-fill
        href: index.xml
  google-analytics:
    tracking-id: "G-744F7V6HLG"
    anonymize-ip: true

format:
  html:
    theme:
      light: [journal, custom-light.scss]
      dark: [journal, custom-dark.scss]
    code-line-numbers: true
      
execute:
  freeze: auto  
comments:
  giscus:
    repo: lektorodd/lektorodd.github.io



