project:
  type: website

website:
  title: "Torodd F. Ottestad"
  site-url: https://lektorodd.github.io
  description: "Blogg med digitale tips og triks i skulen"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lektorodd/lektorodd.github.io
      - icon: mastodon
        href: https://snabelen.no/@torodd
      - icon: youtube
        href: https://www.youtube.com/channel/UCWfDrIj3Mq3Niz77HJ6cTNg
      - icon: linkedin
        href: https://linkedin.com/in/torodd-ottestad-b2583a59
      - icon: rss-fill
        href: index.xml
  google-analytics:
    tracking-id: "G-744F7V6HLG"
    anonymize-ip: true

format:
  html:
    theme: 
    - journal
    - custom.scss
    code-line-numbers: true
execute:
  freeze: auto  
comments:
  giscus:
    repo: lektorodd/lektorodd.github.io



